filebeat.prospectors:
- input_type: log
  paths:
    - /usr/local/nginx/logs/app_access.log
  document_type: nginx-access-app
- input_type: log
  paths:
    - /s1forumdata/logs/*.log
  document_type: nginx-access-bbs

output.logstash:
  hosts: ["192.168.2.99:5044"]
  proxy_url: socks5://Stage1st-APP3:1080
  worker: 4
  bulk_max_size: 8192
